name: Build Error Code Inspector

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  run-tests:
    name: Run unit tests
    if: always()

    runs-on: ubuntu-latest
    env:
      JAVA_VER: 8
    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK ${{ matrix.jdk }}"
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: "Chmod mvnw"
        run: chmod +x mvnw

      - name: "Build Error Code Inspector"
        run: |
          cd dubbo-error-code-inspector
          ../mvnw --batch-mode --no-snapshot-updates -e --no-transfer-progress --fail-fast clean install -DskipTests=true -DskipIntegrationTests=true -Dcheckstyle.skip=true -Dcheckstyle_unix.skip=true -Drat.skip=true -Dmaven.javadoc.skip=true
          
      - name: "Upload Error Code Inspector Package"
        if: ${{ startsWith( matrix.os, 'ubuntu') && startsWith( matrix.jdk, '17') }}
        uses: actions/upload-artifact@v2
        with:
          name: "error-inspection-result.txt"
          path: dubbo-error-code-inspector/target/dubbo-error-code-inspector-1.0.0-SNAPSHOT.jar